package com.example.helloworld;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Button;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button btn= findViewById(R.id. button_reset);
        btn.setOnClickListener(new View.OnClickListener(){
            public void onClick(View v) {
                EditText editText= findViewById(R.id.e1);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e2);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e3);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e4);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e5);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e6);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e7);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e8);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e9);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e10);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e11);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e12);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e13);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e14);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e15);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e16);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e17);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e18);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e19);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e20);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e21);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e22);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e23);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e24);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e25);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e26);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e27);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e28);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e29);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e30);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e31);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e32);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e33);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e34);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e35);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e36);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e37);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e38);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e39);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e40);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e41);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e42);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e43);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e44);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e45);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e46);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e47);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e48);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e49);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e50);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e51);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e52);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e53);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e54);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e55);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e56);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e57);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e58);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e59);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e60);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e61);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e62);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e63);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e64);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e65);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e66);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e67);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e68);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e69);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e70);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e71);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e72);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e73);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e74);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e75);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e76);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e77);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e78);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e79);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e80);
                editText.setText("0",TextView.BufferType.EDITABLE);
                editText= findViewById(R.id.e81);
                editText.setText("0",TextView.BufferType.EDITABLE);
            }
        });
        Button btn2= findViewById(R.id. button_solve);
        btn2.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                int[][] board=new int[][]{
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0},
                        {0,0,0,0,0,0,0,0,0}};

                EditText edit = findViewById(R.id.e1);
                String number = edit.getText().toString();
                board[0][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e2);
                number = edit.getText().toString();
                board[0][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e3);
                number = edit.getText().toString();
                board[0][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e4);
                number = edit.getText().toString();
                board[0][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e5);
                number = edit.getText().toString();
                board[0][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e6);
                number = edit.getText().toString();
                board[0][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e7);
                number = edit.getText().toString();
                board[0][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e8);
                number = edit.getText().toString();
                board[0][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e9);
                number = edit.getText().toString();
                board[0][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e10);
                number = edit.getText().toString();
                board[1][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e11);
                number = edit.getText().toString();
                board[1][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e12);
                number = edit.getText().toString();
                board[1][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e13);
                number = edit.getText().toString();
                board[1][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e14);
                number = edit.getText().toString();
                board[1][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e15);
                number = edit.getText().toString();
                board[1][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e16);
                number = edit.getText().toString();
                board[1][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e17);
                number = edit.getText().toString();
                board[1][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e18);
                number = edit.getText().toString();
                board[1][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e19);
                number = edit.getText().toString();
                board[2][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e20);
                number = edit.getText().toString();
                board[2][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e21);
                number = edit.getText().toString();
                board[2][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e22);
                number = edit.getText().toString();
                board[2][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e23);
                number = edit.getText().toString();
                board[2][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e24);
                number = edit.getText().toString();
                board[2][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e25);
                number = edit.getText().toString();
                board[2][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e26);
                number = edit.getText().toString();
                board[2][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e27);
                number = edit.getText().toString();
                board[2][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e28);
                number = edit.getText().toString();
                board[3][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e29);
                number = edit.getText().toString();
                board[3][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e30);
                number = edit.getText().toString();
                board[3][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e31);
                number = edit.getText().toString();
                board[3][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e32);
                number = edit.getText().toString();
                board[3][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e33);
                number = edit.getText().toString();
                board[3][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e34);
                number = edit.getText().toString();
                board[3][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e35);
                number = edit.getText().toString();
                board[3][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e36);
                number = edit.getText().toString();
                board[3][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e37);
                number = edit.getText().toString();
                board[4][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e38);
                number = edit.getText().toString();
                board[4][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e39);
                number = edit.getText().toString();
                board[4][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e40);
                number = edit.getText().toString();
                board[4][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e41);
                number = edit.getText().toString();
                board[4][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e42);
                number = edit.getText().toString();
                board[4][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e43);
                number = edit.getText().toString();
                board[4][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e44);
                number = edit.getText().toString();
                board[4][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e45);
                number = edit.getText().toString();
                board[4][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e46);
                number = edit.getText().toString();
                board[5][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e47);
                number = edit.getText().toString();
                board[5][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e48);
                number = edit.getText().toString();
                board[5][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e49);
                number = edit.getText().toString();
                board[5][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e50);
                number = edit.getText().toString();
                board[5][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e51);
                number = edit.getText().toString();
                board[5][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e52);
                number = edit.getText().toString();
                board[5][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e53);
                number = edit.getText().toString();
                board[5][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e54);
                number = edit.getText().toString();
                board[5][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e55);
                number = edit.getText().toString();
                board[6][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e56);
                number = edit.getText().toString();
                board[6][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e57);
                number = edit.getText().toString();
                board[6][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e58);
                number = edit.getText().toString();
                board[6][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e59);
                number = edit.getText().toString();
                board[6][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e60);
                number = edit.getText().toString();
                board[6][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e61);
                number = edit.getText().toString();
                board[6][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e62);
                number = edit.getText().toString();
                board[6][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e63);
                number = edit.getText().toString();
                board[6][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e64);
                number = edit.getText().toString();
                board[7][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e65);
                number = edit.getText().toString();
                board[7][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e66);
                number = edit.getText().toString();
                board[7][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e67);
                number = edit.getText().toString();
                board[7][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e68);
                number = edit.getText().toString();
                board[7][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e69);
                number = edit.getText().toString();
                board[7][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e70);
                number = edit.getText().toString();
                board[7][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e71);
                number = edit.getText().toString();
                board[7][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e72);
                number = edit.getText().toString();
                board[7][8] = Integer.parseInt(number);
                edit = findViewById(R.id.e73);
                number = edit.getText().toString();
                board[8][0] = Integer.parseInt(number);
                edit = findViewById(R.id.e74);
                number = edit.getText().toString();
                board[8][1] = Integer.parseInt(number);
                edit = findViewById(R.id.e75);
                number = edit.getText().toString();
                board[8][2] = Integer.parseInt(number);
                edit = findViewById(R.id.e76);
                number = edit.getText().toString();
                board[8][3] = Integer.parseInt(number);
                edit = findViewById(R.id.e77);
                number = edit.getText().toString();
                board[8][4] = Integer.parseInt(number);
                edit = findViewById(R.id.e78);
                number = edit.getText().toString();
                board[8][5] = Integer.parseInt(number);
                edit = findViewById(R.id.e79);
                number = edit.getText().toString();
                board[8][6] = Integer.parseInt(number);
                edit = findViewById(R.id.e80);
                number = edit.getText().toString();
                board[8][7] = Integer.parseInt(number);
                edit = findViewById(R.id.e81);
                number = edit.getText().toString();
                board[8][8] = Integer.parseInt(number);
                int N = board.length;

                if (solve.solveSudoku(board, N))
                {
                    EditText editText= findViewById(R.id.e1);
                    editText.setText(Integer.toString(board[0][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e2);
                    editText.setText(Integer.toString(board[0][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e3);
                    editText.setText(Integer.toString(board[0][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e4);
                    editText.setText(Integer.toString(board[0][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e5);
                    editText.setText(Integer.toString(board[0][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e6);
                    editText.setText(Integer.toString(board[0][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e7);
                    editText.setText(Integer.toString(board[0][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e8);
                    editText.setText(Integer.toString(board[0][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e9);
                    editText.setText(Integer.toString(board[0][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e10);
                    editText.setText(Integer.toString(board[1][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e11);
                    editText.setText(Integer.toString(board[1][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e12);
                    editText.setText(Integer.toString(board[1][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e13);
                    editText.setText(Integer.toString(board[1][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e14);
                    editText.setText(Integer.toString(board[1][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e15);
                    editText.setText(Integer.toString(board[1][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e16);
                    editText.setText(Integer.toString(board[1][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e17);
                    editText.setText(Integer.toString(board[1][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e18);
                    editText.setText(Integer.toString(board[1][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e19);
                    editText.setText(Integer.toString(board[2][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e20);
                    editText.setText(Integer.toString(board[2][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e21);
                    editText.setText(Integer.toString(board[2][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e22);
                    editText.setText(Integer.toString(board[2][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e23);
                    editText.setText(Integer.toString(board[2][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e24);
                    editText.setText(Integer.toString(board[2][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e25);
                    editText.setText(Integer.toString(board[2][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e26);
                    editText.setText(Integer.toString(board[2][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e27);
                    editText.setText(Integer.toString(board[2][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e28);
                    editText.setText(Integer.toString(board[3][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e29);
                    editText.setText(Integer.toString(board[3][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e30);
                    editText.setText(Integer.toString(board[3][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e31);
                    editText.setText(Integer.toString(board[3][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e32);
                    editText.setText(Integer.toString(board[3][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e33);
                    editText.setText(Integer.toString(board[3][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e34);
                    editText.setText(Integer.toString(board[3][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e35);
                    editText.setText(Integer.toString(board[3][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e36);
                    editText.setText(Integer.toString(board[3][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e37);
                    editText.setText(Integer.toString(board[4][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e38);
                    editText.setText(Integer.toString(board[4][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e39);
                    editText.setText(Integer.toString(board[4][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e40);
                    editText.setText(Integer.toString(board[4][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e41);
                    editText.setText(Integer.toString(board[4][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e42);
                    editText.setText(Integer.toString(board[4][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e43);
                    editText.setText(Integer.toString(board[4][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e44);
                    editText.setText(Integer.toString(board[4][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e45);
                    editText.setText(Integer.toString(board[4][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e46);
                    editText.setText(Integer.toString(board[5][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e47);
                    editText.setText(Integer.toString(board[5][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e48);
                    editText.setText(Integer.toString(board[5][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e49);
                    editText.setText(Integer.toString(board[5][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e50);
                    editText.setText(Integer.toString(board[5][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e51);
                    editText.setText(Integer.toString(board[5][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e52);
                    editText.setText(Integer.toString(board[5][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e53);
                    editText.setText(Integer.toString(board[5][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e54);
                    editText.setText(Integer.toString(board[5][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e55);
                    editText.setText(Integer.toString(board[6][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e56);
                    editText.setText(Integer.toString(board[6][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e57);
                    editText.setText(Integer.toString(board[6][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e58);
                    editText.setText(Integer.toString(board[6][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e59);
                    editText.setText(Integer.toString(board[6][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e60);
                    editText.setText(Integer.toString(board[6][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e61);
                    editText.setText(Integer.toString(board[6][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e62);
                    editText.setText(Integer.toString(board[6][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e63);
                    editText.setText(Integer.toString(board[6][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e64);
                    editText.setText(Integer.toString(board[7][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e65);
                    editText.setText(Integer.toString(board[7][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e66);
                    editText.setText(Integer.toString(board[7][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e67);
                    editText.setText(Integer.toString(board[7][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e68);
                    editText.setText(Integer.toString(board[7][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e69);
                    editText.setText(Integer.toString(board[7][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e70);
                    editText.setText(Integer.toString(board[7][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e71);
                    editText.setText(Integer.toString(board[7][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e72);
                    editText.setText(Integer.toString(board[7][8]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e73);
                    editText.setText(Integer.toString(board[8][0]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e74);
                    editText.setText(Integer.toString(board[8][1]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e75);
                    editText.setText(Integer.toString(board[8][2]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e76);
                    editText.setText(Integer.toString(board[8][3]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e77);
                    editText.setText(Integer.toString(board[8][4]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e78);
                    editText.setText(Integer.toString(board[8][5]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e79);
                    editText.setText(Integer.toString(board[8][6]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e80);
                    editText.setText(Integer.toString(board[8][7]),TextView.BufferType.EDITABLE);
                    editText= findViewById(R.id.e81);
                    editText.setText(Integer.toString(board[8][8]),TextView.BufferType.EDITABLE);
                }
                else
                {
                    TextView Text= findViewById(R.id.text);
                    Text.setText("Invalid entries");
                }
            }
        });
    }
}
